export const SIGN_IN_WITH_EMAIL = 'auth/SIGN_IN_WITH_EMAIL';

export const BECOME_A_SELLER = 'auth/BECOME_A_SELLER';
export const UPDATE_SELLER = 'auth/UPDATE_SELLER';
export const BECOME_A_SELLER_SUCCESS = 'auth/BECOME_A_SELLER_SUCCESS';

export const SIGN_IN_WITH_EMAIL_SUCCESS = 'auth/SIGN_IN_WITH_EMAIL_SUCCESS';
export const SIGN_UP_WITH_EMAIL = 'auth/SIGN_UP_WITH_EMAIL';

export const CATEGORY_LIST_SUCCESS = 'auth/CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_LOADER_SUCCESS = 'auth/CATEGORY_LIST_LOADER_SUCCESS'
export const CATEGORY_LIST_LOADER_ERROR = 'auth/CATEGORY_LIST_LOADER_ERROR'
export const GET_CATEGORY_LIST = 'auth/GET_CATEGORY_LIST'
export const CATEGORY_LIST_LOADER = 'auth/CATEGORY_LIST_LOADER';

export const GET_HOME_VENDORS = 'auth/GET_HOME_VENDORS'
export const HOME_VENDORS_SUCCESS = 'auth/HOME_VENDORS_SUCCESS'
export const VENDORS_LIST_LOADER = 'auth/VENDORS_LIST_LOADER'
export const VENDORS_LIST_LOADER_SUCCESS = 'auth/VENDORS_LIST_LOADER_SUCCESS'
export const VENDORS_LIST_LOADER_ERROR = 'auth/VENDORS_LIST_LOADER_ERROR'

export const GET_HOME_NEW_ARRIVALS = 'auth/GET_HOME_NEW_ARRIVALS'
export const HOME_NEW_ARRIVALS_SUCCESS = 'auth/HOME_NEW_ARRIVALS_SUCCESS'
export const HOME_NEW_ARRIVALS_LOADER = 'auth/HOME_NEW_ARRIVALS_LOADER'
export const HOME_NEW_ARRIVALS_LOADER_SUCCESS = 'auth/HOME_NEW_ARRIVALS_LOADER_SUCCESS'
export const HOME_NEW_ARRIVALS_LOADER_ERROR = 'auth/HOME_NEW_ARRIVALS_LOADER_ERROR'

export const GET_USER_DETAILS = 'auth/GET_USER_DETAILS'
export const GET_USER_DETAIL_SUCCESS = 'auth/GET_USER_DETAIL_SUCCESS'
export const GET_USER_DETAIL_LOADER = 'auth/GET_USER_DETAIL_LOADER'
export const GET_USER_DETAIL_LOADER_SUCCESS = 'auth/GET_USER_DETAIL_LOADER_SUCCESS'
export const GET_USER_DETAIL_LOADER_ERROR = 'auth/GET_USER_DETAIL_LOADER_ERROR'


export const GET_PRODUCT_BY_VENDOR = 'auth/GET_PRODUCT_BY_VENDOR'
export const VENDORS_PRODUCTS_LIST_LOADER = 'auth/VENDORS_PRODUCTS_LIST_LOADER'
export const VENDORS_PRODUCTS_LIST_LOADER_SUCCESS = 'auth/VENDORS_PRODUCTS_LIST_LOADER_SUCCESS'
export const VENDORS_PRODUCTS_LIST_SUCCESS = 'auth/VENDORS_PRODUCTS_LIST_SUCCESS'
export const VENDORS_PRODUCTS_LIST_LOADER_ERROR = 'auth/VENDORS_PRODUCTS_LIST_LOADER_ERROR'

export const HOME_CATEGORIES_SUCCESS = 'auth/HOME_CATEGORIES_SUCCESS'
export const HOME_CATEGORIES_LOADER = 'auth/HOME_CATEGORIES_LOADER'
export const HOME_CATEGORIES_LOADER_SUCCESS = 'auth/HOME_CATEGORIES_LOADER_SUCCESS'
export const HOME_CATEGORIES_LOADER_ERROR = 'auth/HOME_CATEGORIES_LOADER_ERROR'
export const GET_HOME_CATEGORIES = 'auth/GET_HOME_CATEGORIES'



export const GET_SELLER_DETAILS = 'auth/GET_SELLER_DETAILS'
export const GET_SELLER_DETAILS_SUCCESS = 'auth/GET_SELLER_DETAILS_SUCCESS'


export const ADD_PRODUCT = 'auth/ADD_PRODUCT';
export const ADD_PRODUCT_LOADING_TRUE = 'auth/ADD_PRODUCT_LOADING_TRUE'
export const ADD_PRODUCT_LOADING_FALSE = 'auth/ADD_PRODUCT_LOADING_FALSE'


export const SIGN_IN_WITH_EMAIL_ERROR = 'auth/SIGN_IN_WITH_EMAIL_ERROR';

export const SIGN_UP_WITH_EMAIL_SUCCESS = 'auth/SIGN_UP_WITH_EMAIL_SUCCESS';
export const SIGN_UP_WITH_EMAIL_ERROR = 'auth/SIGN_UP_WITH_EMAIL_ERROR';

export const SIGN_IN_WITH_MOBILE = 'auth/SIGN_IN_WITH_MOBILE';
export const SIGN_IN_WITH_MOBILE_ERROR = 'auth/SIGN_IN_WITH_MOBILE_ERROR';

export const SIGN_IN_WITH_GOOGLE = 'auth/SIGN_IN_WITH_GOOGLE';
export const SIGN_IN_WITH_GOOGLE_ERROR = 'auth/SIGN_IN_WITH_GOOGLE_ERROR';
export const SIGN_IN_WITH_GOOGLE_CANCEL = 'auth/SIGN_IN_WITH_GOOGLE_CANCEL';

export const SIGN_IN_WITH_FACEBOOK = 'auth/SIGN_IN_WITH_FACEBOOK';
export const SIGN_IN_WITH_FACEBOOK_ERROR = 'auth/SIGN_IN_WITH_FACEBOOK_ERROR';
export const SIGN_IN_WITH_FACEBOOK_CANCEL = 'auth/SIGN_IN_WITH_FACEBOOK_CANCEL';

export const SIGN_IN_WITH_APPLE = 'auth/SIGN_IN_WITH_APPLE';
export const SIGN_IN_WITH_APPLE_ERROR = 'auth/SIGN_IN_WITH_APPLE_ERROR';
export const SIGN_IN_WITH_APPLE_CANCEL = 'auth/SIGN_IN_WITH_APPLE_CANCEL';

export const FORGOT_PASSWORD = 'auth/FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'auth/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'auth/FORGOT_PASSWORD_ERROR';

export const CHECK_AUTH = 'auth/CHECK_AUTH';

export const IS_LOGIN = 'auth/IS_LOGIN';

export const SIGN_OUT = 'auth/SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'auth/SIGN_OUT_SUCCESS';

export const CHANGE_EMAIL = 'auth/CHANGE_EMAIL';
export const CHANGE_EMAIL_SUCCESS = 'auth/CHANGE_EMAIL_SUCCESS';
export const CHANGE_EMAIL_ERROR = 'auth/CHANGE_EMAIL_ERROR';

export const CHANGE_PASSWORD = 'auth/CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'auth/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'auth/CHANGE_PASSWORD_ERROR';

export const GET_CUSTOMER = 'auth/GET_CUSTOMER';
export const GET_CUSTOMER_SUCCESS = 'auth/GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_ERROR = 'auth/GET_CUSTOMER_ERROR';

export const UPDATE_SHIPPING_ADDRESS_SUCCESS =
  'auth/UPDATE_SHIPPING_ADDRESS_SUCCESS';

export const UPDATE_CUSTOMER = 'auth/UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'auth/UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_ERROR = 'auth/UPDATE_CUSTOMER_ERROR';

export const REGISTER_OREO_USER = 'auth/REGISTER_OREO_USER';
export const REGISTER_OREO_USER_SUCCESS = 'auth/REGISTER_OREO_USER_SUCCESS';
export const REGISTER_OREO_USER_ERROR = 'auth/REGISTER_OREO_USER_ERROR';

export const UPDATE_USER_SUCCESS = 'auth/UPDATE_USER_SUCCESS';

export const SIGN_UP_WITH_OTP = 'auth/SIGN_UP_WITH_OTP';
export const SIGN_UP_WITH_OTP_SUCCESS = 'auth/SIGN_UP_WITH_OTP_SUCCESS';
export const SIGN_UP_WITH_OTP_ERROR = 'auth/SIGN_UP_WITH_OTP_ERROR';

export const SIGN_IN_WITH_OTP = 'auth/SIGN_IN_WITH_OTP';
export const SIGN_IN_WITH_OTP_SUCCESS = 'auth/SIGN_IN_WITH_OTP_SUCCESS';
export const SIGN_IN_WITH_OTP_ERROR = 'auth/SIGN_IN_WITH_OTP_ERROR';

export const GET_LIST_FILE_DOWNLOAD = 'auth/GET_LIST_FILE_DOWNLOAD';
export const GET_LIST_FILE_DOWNLOAD_SUCCESS =
  'auth/GET_LIST_FILE_DOWNLOAD_SUCCESS';
export const GET_LIST_FILE_DOWNLOAD_ERROR = 'auth/GET_LIST_FILE_DOWNLOAD_ERROR';
export const UPDATE_USER_LOGO = 'auth/UPDATE_USER_LOGO';
export const UPDATE_USER_LOGO_SUCCESS = 'auth/UPDATE_USER_LOGO_SUCCESS';
export const UPDATE_USER_LOGO_ERROR = 'auth/UPDATE_USER_LOGO_ERROR';
